#pragma once

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KH2FM_Toolkit
{
	namespace Properties
	{
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//[System::Runtime::CompilerServices::CompilerGeneratedAttribute(), System::CodeDom::Compiler::GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
		class Settings : public System::Configuration::ApplicationSettingsBase
		{

		private:
			static Settings *defaultInstance;

		public:
			const static Settings &getDefault() const;
		};
	}
}
