#pragma once

#include <string>

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KH2FM_Toolkit
{
	namespace Properties
	{
//C# TO C++ CONVERTER TODO TASK: The .NET System namespace is not available from native C++:
//		using namespace System;


		/// <summary>
		///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
		/// </summary>
		// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
		// à l'aide d'un outil, tel que ResGen ou Visual Studio.
		// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
		// avec l'option /str ou régénérez votre projet VS.
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//[System::CodeDom::Compiler::GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System::Diagnostics::DebuggerNonUserCodeAttribute(), System::Runtime::CompilerServices::CompilerGeneratedAttribute()]
		class Resources
		{

		private:
			static System::Resources::ResourceManager *resourceMan;

			static System::Globalization::CultureInfo *resourceCulture;

		public:
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//[System::Diagnostics::CodeAnalysis::SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
			Resources();

			/// <summary>
			///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//[System::ComponentModel::EditorBrowsableAttribute(System::ComponentModel::EditorBrowsableState::Advanced)]
			const static System::Resources::ResourceManager &getResourceManager() const;

			/// <summary>
			///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
			///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
			/// </summary>
//C# TO C++ CONVERTER NOTE: The following .NET attribute has no direct equivalent in native C++:
//[System::ComponentModel::EditorBrowsableAttribute(System::ComponentModel::EditorBrowsableState::Advanced)]
			const static System::Globalization::CultureInfo &getCulture() const;
			static void setCulture(const System::Globalization::CultureInfo &value);

			/// <summary>
			///   Recherche une ressource localisée de type System.Byte[].
			/// </summary>
			const static unsigned char *getHashList() const;

			/// <summary>
			///   Recherche une chaîne localisée semblable à This tool is able to extract and modify the iso of the game Kingdom Hearts 2(Final Mix)
			///It uses a list that gives all of the ISO resource names in clear (msg/jp/al.bar) instead of their hashes(0x56203d96).
			///This list isn&apos;t complete yet but contains all the files needed for the translation.
			///
			///This tool can launch more than one patch and mix them instead to have to apply them one by one.
			///Simply drag &apos;n drop all patches you need to apply to the toolkit or, with the 
			///windows cmd, execute the command(in the  [le reste de la chaîne a été tronqué]&quot;;.
			/// </summary>
			const static std::string &getReadme() const;
		};
	}
}
